### PR TITLE
Added index.html and style.css

### PR DESCRIPTION
**Pull request by c-franklin**
Hello.

I've just started working in Elm – I've come from using Angular and Knockout. Very glad to have found a router for Elm :-)

It took me a while to figure out which files I needed to start up the router – so I added an index.html and also turned the layout table in a div layout and added style.css – these files may be useful to beginners I hope!

(Also – I've added .idea to the .gitignore which you may want to remove).

Thank you. Charlotte

### CODE REVIEW

**Comment by rgrempel** [comment]
Thanks for this!

I'm going to be away for a week, so I won't be able to look at this right away. But I just wanted to acknowledge it in the meantime.

**Comment by amitaibu** [comment]
> It took me a while to figure out which files I needed to start up the router

I think a better solution would be to document that the `elm-reactor` is/ can be used to see the examples

**Comment by c-franklin** [comment]
Sounds good. 

I deleted the index.html and ran `elm reactor` - but couldn't figure out how to view any pages without the index.html. What would the instructions be for using `elm reactor` on its own? 

For now – I put index.html back in and added instructions at top of readme to run up `elm reactor` plus the URL to view.

**Comment by rgrempel** [comment]
My apologies for not getting back to this until now!

I've added some documentation to [the example](https://github.com/rgrempel/elm-route-hash/tree/master/examples/elm-architecture-tutorial) that mentions using elm-reactor to run the examples locally -- that probably is the easiest way to do it. And, now there are three different variations on the example (so three different files to start with when compiling, or using elm-reactor).

**Pull request closed without merging**
